services:
  app:
    build:
      context: '.docker/php-fpm'
      target: os
    working_dir: /laravel/current
    volumes:
      - './:/laravel/current'
    networks:
      - amber-cms

  nginx:
    build:
      context: '.docker/nginx'
    depends_on:
      - php-fpm
    volumes:
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites
    ports:
      - '${NGINX_HOST_HTTPS_PORT}:443'
      - '${NGINX_HOST_HTTP_PORT}:80'
    networks:
      - amber-cms

  php-fpm:
    build:
      context: '.docker/php-fpm'
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    networks:
      - amber-cms
    expose:
      - '9000'

  pgsql:
    image: 'postgres:17'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'amber-cms-pgsql:/var/lib/postgresql/data'
    networks:
      - amber-cms
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'amber-cms-redis:/data'
    networks:
      - amber-cms
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - amber-cms

networks:
  amber-cms:
    driver: bridge

volumes:
  amber-cms-pgsql:
    driver: local
  amber-cms-redis:
    driver: local
